### ISSUE TITLE
Warnings triggered on database-end by health-monitor

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/Monitor-bundle#1]
When going to https://engine.example.org/health, it triggers a warning on the database-end:

> May 22 14:36:13 database-1 mysqld: 2018-05-22 14:36:13 140580659341056 [Warning] Aborted connection 8701 to db: 'engineblock' user: 'engineblock' host: '10.2.16.3' (Got an error reading communication packets)

This only happens for engine and can be easily reproduced by going to the health-endpoint in a browser.
I've excluded HAproxy, loadbalancer, host-firewall and SElinux as a possible cause.. It seems to be a Doctrine-thing, since a `SELECT 1;` from CLI or some graphical tool is running just fine.

**Comment by MKodde** [comment]
This issue has been addressed in this #2
