### ISSUE TITLE
Add a recipe

### ISSUE THREAD

**Issue by tacman** [OpenConext/Monitor-bundle#14]
since the bundle can't run without adding the routing, it'd be great if there were a recipe.

Since Symfony recipes are a pain, I've started using https://github.com/endroid/installer.

I can make a PR with that if you're okay with using that package.  You can see his installer package in action at https://github.com/endroid/qr-code-bundle.

This is a nice bundle, thanks for releasing it.

**Comment by thijskh** [comment]
Hi, this is a great suggestion. We'd welcome a PR based on `endroid/installer`.
